# Generated by Django 2.1.5 on 2019-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190420_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
