# Generated by Django 2.2.4 on 2020-02-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
