# Generated by Django 2.2.4 on 2021-10-20 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211005_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.TextField(blank=True, null=True)),
                ('hash_digest', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.TextField(blank=True, null=True)),
                ('hash_digest', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserDistrictDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('district_dashboard_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DistrictDashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomSearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
