# Generated by Django 2.2.4 on 2021-10-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211023_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsearch',
            name='query_string_hash_digest',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='districtdashboard',
            name='query_string_hash_digest',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
