# Generated by Django 2.2.4 on 2021-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211023_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomsearch',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userdistrictdashboard',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
