# Generated by Django 2.2.4 on 2021-10-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211023_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomsearch',
            name='last_notified_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userdistrictdashboard',
            name='last_notified_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
