# Generated by Django 2.2.4 on 2021-11-07 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211026_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomsearch',
            name='last_notified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercustomsearch',
            name='last_number_of_results',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
