# Generated by Django 2.2.4 on 2021-11-17 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211107_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarkedproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
