# Generated by Django 2.2.4 on 2021-11-23 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customsearch_frontend_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(blank=True, max_length=25, null=True)),
                ('organization_email', models.TextField(blank=True, null=True, unique=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(blank=True, db_column='customuser', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
