# Generated by Django 2.2.4 on 2021-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211128_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarkedproperty',
            name='bbl',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='userbookmarkedproperty',
            unique_together={('id', 'bbl')},
        ),
    ]
