# Generated by Django 2.2.4 on 2021-12-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211202_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookmarkedproperty',
            unique_together={('user', 'bbl')},
        ),
    ]
