# Generated by Django 2.2.4 on 2021-12-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20211202_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomsearch',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
