# Generated by Django 2.2.4 on 2021-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211208_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdistrictdashboard',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='usercustomsearch',
            unique_together={('user', 'name')},
        ),
    ]
