# Generated by Django 2.2.4 on 2021-12-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211208_0039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdistrictdashboard',
            unique_together={('user', 'name')},
        ),
    ]
