# Generated by Django 2.2.4 on 2022-04-14 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211208_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomsearch',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
