# Generated by Django 4.2.11 on 2026-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_accessrequest_id_alter_customsearch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomsearch',
            name='last_notified_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercustomsearch',
            name='last_notified_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userdistrictdashboard',
            name='last_notified_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
