# Generated by Django 4.2.11 on 2026-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_usercustomsearch_last_notified_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomsearch',
            name='last_notified_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userdistrictdashboard',
            name='last_notified_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
