# Generated by Django 4.2.29 on 2026-10-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_mfa_totp_passkey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passkeycredential',
            new_name='users_passk_user_id_c9d681_idx',
            old_name='users_passk_user_id_6f0b0d_idx',
        ),
    ]
