# Generated by Django 2.1.5 on 2019-02-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='model_name',
            field=models.CharField(choices=[('Council', 'Council'), ('Property', 'Property'), ('Building', 'Building'), ('AcrisRealLegal', 'AcrisRealLegal'), ('AcrisRealMaster', 'AcrisRealMaster'), ('AcrisRealParty', 'AcrisRealParty'), ('CoreSubsidyRecord', 'CoreSubsidyRecord'), ('DOBComplaint', 'DOBComplaint'), ('DOBPermitFiledLegacy', 'DOBPermitFiledLegacy'), ('DOBPermitIssuedLegacy', 'DOBPermitIssuedLegacy'), ('DOBPermitIssuedNow', 'DOBPermitIssuedNow'), ('DOBPermitIssuedJoined', 'DOBPermitIssuedJoined'), ('DOBViolation', 'DOBViolation'), ('ECBViolation', 'ECBViolation'), ('Eviction', 'Eviction'), ('HousingLitigation', 'HousingLitigation'), ('HPDBuildingRecord', 'HPDBuildingRecord'), ('HPDComplaint', 'HPDComplaint'), ('HPDProblem', 'HPDProblem'), ('HPDContact', 'HPDContact'), ('HPDRegistration', 'HPDRegistration'), ('HPDViolation', 'HPDViolation'), ('RentStabilizationRecord', 'RentStabilizationRecord'), ('SubsidyJ51', 'SubsidyJ51'), ('Subsidy421a', 'Subsidy421a'), ('PublicHousingRecord', 'PublicHousingRecord'), ('TaxLien', 'TaxLien'), ('LisPenden', 'LisPenden'), ('LisPendenComment', 'LisPendenComment'), ('AddressRecord', 'AddressRecord')], max_length=255, unique=True),
        ),
    ]
