# Generated by Django 2.1 on 2019-02-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='File is required for standard updates, Dataset Name required for join table updates', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Dataset'),
        ),
        migrations.AlterField(
            model_name='update',
            name='file',
            field=models.ForeignKey(blank=True, help_text='File is required for standard updates, Dataset Name required for join table updates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_file', to='core.DataFile'),
        ),
    ]
