# Generated by Django 2.1.5 on 2019-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190228_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, choices=[('reported', 'Reported'), ('duplicate', 'Duplicate'), ('investigating', 'Investigating'), ('fixed', 'Fixed'), ('unable', 'Unable to reproduce')], default='reported', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
