# Generated by Django 2.1.5 on 2019-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190214_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='model_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
