# Generated by Django 2.2.4 on 2019-10-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset_api_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='records_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='records_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='update_schedule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('when needed', 'When Needed')], max_length=255, null=True),
        ),
    ]
