# Generated by Django 2.2.4 on 2020-02-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190930_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugReport',
            new_name='UserMessage',
        ),
    ]
