# Generated by Django 2.1.5 on 2019-02-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='version',
        ),
        migrations.AddField(
            model_name='datafile',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
